<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Carbon\Carbon;

class QrCode extends Model
{
    use HasFactory;

    protected $fillable = [
        'generated_by',
        'code',
        'valid_date',
        'generated_at_time',
        'expires_at',
        'is_active',
    ];

    protected $casts = [
        'valid_date' => 'date',
        'expires_at' => 'datetime',
        'is_active' => 'boolean',
    ];

    /**
     * Relationship: QR code generated by user (security/admin)
     */
    public function generatedBy()
    {
        return $this->belongsTo(User::class, 'generated_by');
    }

    /**
     * Check if QR code is still valid
     */
    public function isValid(): bool
    {
        return $this->is_active 
            && $this->valid_date->isToday() 
            && Carbon::now()->lessThan($this->expires_at);
    }

    /**
     * Deactivate this QR code
     */
    public function deactivate(): void
    {
        $this->is_active = false;
        $this->save();
    }

    /**
     * Generate unique QR code string
     */
    public static function generateUniqueCode(): string
    {
        do {
            // Format: YYYYMMDD-RANDOM8CHARS
            $code = date('Ymd') . '-' . strtoupper(substr(md5(uniqid(rand(), true)), 0, 8));
        } while (self::where('code', $code)->exists());

        return $code;
    }
}
